import { Card, CardContent } from "@/components/ui/card";
import { BookOpen, Sprout, Wind, Droplets } from "lucide-react";

export default function Learn() {
  const articles = [
    {
      title: "Understanding Your Carbon Footprint",
      category: "Basics",
      readTime: "5 min read",
      icon: Wind,
      color: "text-blue-500",
      bg: "bg-blue-100",
      content: "A carbon footprint is the total amount of greenhouse gases generated by our actions. It's measured in equivalent tons of CO2. Everything from the food we eat to how we travel contributes to this number."
    },
    {
      title: "The Impact of Fast Fashion",
      category: "Lifestyle",
      readTime: "4 min read",
      icon: Sprout,
      color: "text-green-500",
      bg: "bg-green-100",
      content: "The fashion industry is responsible for 10% of global carbon emissions. By shifting to slow fashion, buying second-hand, and taking care of the clothes we own, we can drastically reduce this impact."
    },
    {
      title: "Water Conservation at Home",
      category: "Home",
      readTime: "6 min read",
      icon: Droplets,
      color: "text-cyan-500",
      bg: "bg-cyan-100",
      content: "Pumping, heating, and treating water requires a massive amount of energy. Fixing leaks, taking shorter showers, and installing low-flow fixtures saves both water and the energy used to process it."
    },
    {
      title: "Plant-Based Diets & The Planet",
      category: "Food",
      readTime: "7 min read",
      icon: BookOpen,
      color: "text-orange-500",
      bg: "bg-orange-100",
      content: "Animal agriculture is a leading cause of deforestation and emissions. You don't have to go fully vegan to make a difference—even replacing meat for just one or two meals a week has a measurable positive impact on your footprint."
    }
  ];

  return (
    <div className="p-6 md:p-10 max-w-5xl mx-auto overflow-y-auto h-full space-y-8">
      <div className="text-center max-w-2xl mx-auto mb-12">
        <h1 className="text-4xl md:text-5xl font-bold font-['Outfit'] tracking-tight mb-4">Learning Hub</h1>
        <p className="text-muted-foreground text-lg">Knowledge is the first step to action. Explore guides and articles to better understand sustainability.</p>
      </div>

      <div className="grid md:grid-cols-2 gap-6">
        {articles.map((article, idx) => (
          <Card key={idx} className="overflow-hidden hover-elevate transition-all border-2 group cursor-pointer">
            <CardContent className="p-0">
              <div className={`h-32 ${article.bg} flex items-center justify-center relative overflow-hidden`}>
                <div className="absolute inset-0 bg-white/20 backdrop-blur-[1px]" />
                <article.icon className={`h-16 w-16 ${article.color} relative z-10 transform group-hover:scale-110 transition-transform duration-500`} />
              </div>
              <div className="p-6">
                <div className="flex items-center gap-3 text-sm text-muted-foreground mb-3 font-medium">
                  <span className="uppercase tracking-wider text-primary">{article.category}</span>
                  <span>•</span>
                  <span>{article.readTime}</span>
                </div>
                <h3 className="text-2xl font-bold font-['Outfit'] mb-3 group-hover:text-primary transition-colors">{article.title}</h3>
                <p className="text-muted-foreground leading-relaxed">{article.content}</p>
                <div className="mt-6 font-semibold text-primary flex items-center gap-1 group-hover:gap-2 transition-all">
                  Read full article &rarr;
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
      </div>
    </div>
  );
}